# -*- coding: utf-8 -*-
"""
Created on Thu Apr 29 14:51:55 2021

@author: Yuanchi Xiao
"""
import pandas as pd
import datetime
#Read data from files generated by the datalogger directly
f=open("ewatering_sa3_sensor",'r')
f.readlines()
# bad_words = ['bad', 'naughty']

# with open('oldfile.txt') as oldfile, open('newfile.txt', 'w') as newfile:
#     for line in oldfile:
#         if not any(bad_word in line for bad_word in bad_words):
#             newfile.write(line)
            
f = open("H:/ewatering_sa3_sensor", "r")
z=f.readlines()
date1 = pd.DataFrame({'count' : []})
count_time=0
count_MO=0
date={}
dht22={}
SA3_MO={}
number={}
# DateTime [] startDate = new DateTime[5];
for i in range(len(z)):
    str1 = ''.join(z[i])    
    try:
        int(str1[0:3])==201
        dat=str1[0:-1]
        count_time=count_time+1
        number[count_time-1]=i
        date[count_time-1]=datetime.strptime(dat,'%Y-%m-%d %H:%M:%S')
        print(date[i])
# # \  df1 = pd.DataFrame(count, index=[date], columns=['count'])
#         if count==1:
#             date1=df1['count']
#         else:
#             date1=date1.join[df1['count']]
    except :
        pass
    if str1[0:8]=='analog,1' and str1[-8:-2].isdigit():
        SA3_MO[0,count_MO]=float(str1[-8:-2])
        print(i)
        print(count_MO)
        
    elif str1[0:8]=='analog,2' and str1[-8:-2].isdigit():
        SA3_MO[1,count_MO]=float(str1[-8:-2])
        print(i)
        print(count_MO)
    elif str1[0:8]=='analog,3' and str1[-8:-2].isdigit():
        SA3_MO[2,count_MO]=float(str1[-8:-2])
        print(i)
        print(count_MO)        
    elif str1[0:8]=='analog,4' and str1[-8:-2].isdigit():
        SA3_MO[3,count_MO]=float(str1[-8:-2])
        print(i)
        print(count_MO)
    elif str1[0:8]=='analog,5' and str1[-8:-2].isdigit():
        SA3_MO[4,count_MO]=float(str1[-8:-2])
        print(i)
        print(count_MO) 
        count_MO=count_MO+1